version: '3'

networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:12.0.3
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
    volumes:
      - ./forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - '3000'  # Remplac√© 'ports' par expose, car accessible via proxy
    ports:
      - '22:22'

  nginx:
    image: nginx:stable
    container_name: forgejo-proxy
    depends_on:
      - server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - '443:443'
    networks:
      - forgejo

