version: '3'

networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo-experimental/forgejo:13
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA_CUSTOM=/data/gitea/
    restart: always
    networks:
      - forgejo
    volumes:
      - type: bind
        source: ./forgejo
        target: /data
        volume_opt:
          o: z  # Applique :Z pour permettre l'Ã©criture

      - /etc/timezone:/etc/timezone:ro  # Lecture seule, pas besoin de :Z
      - /etc/localtime:/etc/localtime:ro # Lecture seule, pas besoin de :Z
    ports:
      - '3000:3000'
      - '22:22'

  docker-in-docker:
    image: docker:dind
    container_name: 'docker_dind'
    privileged: 'true'
    command: ['dockerd', '-H', 'tcp://0.0.0.0:2375', '--tls=false']
    restart: 'unless-stopped'
    volumes:
      - type: bind
        source: ./dind
        target: /var/lib/docker
        volume_opt:
          o: Z

  runner:
    image: 'data.forgejo.org/forgejo/runner:11'
    links:
      - docker-in-docker
    depends_on:
      docker-in-docker:
        condition: service_started
    container_name: 'runner'
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    volumes:
      - ./runner:/data
    restart: 'unless-stopped'

    command: '/bin/sh -c "sleep 5; forgejo-runner daemon"'
